OBJS:=  $(OBJS) core/class.o core/elf_loader.o core/file.o \
	core/filesystem.o core/kernel.o core/api_posix.o\
	core/process.o core/syscalls.o core/device.o core/system.o \
	core/env.o core/user.o core/modulelink.o core/socket.o
	
