OBJS:=  $(OBJS) modules/module.o \
		modules/null.o modules/stdtty.o modules/x86serial.o\
		modules/ide.o modules/bochsvbe.o \
		modules/ext2.o modules/dospartition.o \
		modules/clock_x86.o modules/keys.o

